# Generated by Django 6.0 on 2026-01-03 09:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('dijk', '0001_initial'), ('dijk', '0002_alter_chemin_d_options'), ('dijk', '0003_chemin_d_date'), ('dijk', '0004_cache_adresse_zone'), ('dijk', '0005_cachenomrue_and_more'), ('dijk', '0006_alter_chemin_d_options_and_more'), ('dijk', '0007_amenity_bug'), ('dijk', '0008_alter_ville_code_insee_alter_ville_densité_and_more'), ('dijk', '0009_typeamenity_amenity_horaires_amenity_id_osm_and_more'), ('dijk', '0010_amenity_ville'), ('dijk', '0011_amenity_rue'), ('dijk', '0012_bug_message_d_erreur'), ('dijk', '0013_bug_importance'), ('dijk', '0014_alter_bug_message_d_erreur_alter_typeamenity_nom_osm'), ('dijk', '0015_alter_amenity_id_osm'), ('dijk', '0016_typeamenity_catégorie_alter_typeamenity_nom_osm_and_more'), ('dijk', '0017_rename_amenity_lieu_rename_typeamenity_typelieu'), ('dijk', '0018_rename_texte_tout_lieu_json_initial_bug_contact_and_more'), ('dijk', '0019_rename_type_amenity_lieu_type_lieu'), ('dijk', '0020_alter_ville_code_insee'), ('dijk', '0021_remove_ville_densité_ville_superficie'), ('dijk', '0022_ville_le couple (nom_norm, code_insee) doit être unique'), ('dijk', '0023_alter_ville_code_insee'), ('dijk', '0024_lieu_arête'), ('dijk', '0025_remove_lieu_rue_lieu_adresse'), ('dijk', '0026_alter_cache_adresse_adresse_and_more'), ('dijk', '0027_remove_arête_zone_remove_sommet_zone_arête_ville_and_more'), ('dijk', '0028_rename_ville_arête_villes'), ('dijk', '0029_alter_arête_villes'), ('dijk', '0030_arbrearête_alter_zone_options_segmentarête'), ('dijk', '0031_zone_arbre_arêtes_alter_arbrearête_père_and_more'), ('dijk', '0032_remove_lieu_adresse_ville_lieux_calculés_and_more'), ('dijk', '0033_groupetypelieu'), ('dijk', '0034_groupetypelieu_féminin'), ('dijk', '0035_lieu_nom_norm'), ('dijk', '0036_rename_json_initial_lieu_json_autres_données_and_more'), ('dijk', '0037_rename_json_autres_données_lieu_json_tout'), ('dijk', '0038_lieu_autre_nom'), ('dijk', '0039_zone_inclue_dans'), ('dijk', '0040_zone_cycla_max_zone_cycla_min'), ('dijk', '0041_lieu_num')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200, unique=True)),
                ('nœuds_à_découper', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('nom_norm', models.CharField(max_length=100)),
                ('code', models.IntegerField(null=True)),
                ('code_insee', models.IntegerField()),
                ('population', models.IntegerField()),
                ('densité', models.SmallIntegerField()),
                ('géom_texte', models.TextField(null=True)),
                ('données_présentes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ville_défaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Sommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_osm', models.BigIntegerField(unique=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('zone', models.ManyToManyField(to='dijk.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('nom_norm', models.CharField(max_length=200)),
                ('nœuds_à_découper', models.TextField()),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Chemin_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.BooleanField(default=False)),
                ('p_détour', models.FloatField()),
                ('étapes_texte', models.TextField()),
                ('interdites_texte', models.TextField(blank=True, default=None, null=True)),
                ('utilisateur', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dernier_p_modif', models.FloatField(blank=True, default=None, null=True)),
                ('début', models.CharField(max_length=255)),
                ('fin', models.CharField(max_length=255)),
                ('interdites_début', models.CharField(max_length=255)),
                ('interdites_fin', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Arête',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longueur', models.FloatField()),
                ('cycla', models.FloatField(blank=True, default=None, null=True)),
                ('cycla_défaut', models.FloatField(default=1.0)),
                ('geom', models.TextField()),
                ('nom', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sensInterdit', models.BooleanField(default=False)),
                ('arrivée', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommet_arrivée', to='dijk.sommet')),
                ('départ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommet_départ', to='dijk.sommet')),
                ('rue', models.ManyToManyField(to='dijk.rue')),
                ('zone', models.ManyToManyField(to='dijk.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Ville_Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijk.zone')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('zone', 'ville'), name='Pas de relation en double.')],
            },
        ),
        migrations.CreateModel(
            name='Ville_Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville1', to='dijk.ville')),
                ('ville2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville2', to='dijk.ville')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ville1', 'ville2'), name='Pas de relation ville_ville en double.')],
            },
        ),
        migrations.AddConstraint(
            model_name='rue',
            constraint=models.UniqueConstraint(fields=('nom_norm', 'ville'), name='une seule rue pour chaque nom_norm pour chaque ville.'),
        ),
        migrations.AddConstraint(
            model_name='chemin_d',
            constraint=models.UniqueConstraint(fields=('ar', 'p_détour', 'début', 'fin', 'interdites_début', 'interdites_fin'), name='Pas de chemins en double.'),
        ),
        migrations.AlterModelOptions(
            name='chemin_d',
            options={'ordering': ['-dernier_p_modif']},
        ),
        migrations.AddField(
            model_name='chemin_d',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='chemin_d',
            options={'ordering': ['-dernier_p_modif', 'date']},
        ),
        migrations.AddField(
            model_name='cache_adresse',
            name='ville',
            field=models.ForeignKey(default=25309, on_delete=django.db.models.deletion.CASCADE, to='dijk.ville'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CacheNomRue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('nom_osm', models.CharField(max_length=200)),
                ('ville', models.ForeignKey(default=25309, on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nom', 'ville'), name='Une seule entrée pour chaque (nom, ville).')],
            },
        ),
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='densité',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='géom_texte',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ville',
            name='population',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='TypeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_osm', models.CharField(max_length=200)),
                ('nom_français', models.TextField(blank=True, default=None, null=True)),
                ('catégorie', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('description', models.TextField()),
                ('comment_reproduire', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('message_d_erreur', models.TextField(blank=True, default=None, null=True)),
                ('importance', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField(blank=True, default=None, null=True)),
                ('horaires', models.TextField(blank=True, default=None, null=True)),
                ('id_osm', models.BigIntegerField(unique=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('texte_tout', models.TextField(blank=True, default=None, null=True)),
                ('tél', models.TextField(blank=True, default=None, null=True)),
                ('type_amenity', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dijk.typeamenity')),
                ('ville', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dijk.ville')),
                ('rue', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.rue')),
            ],
        ),
        migrations.AddConstraint(
            model_name='typeamenity',
            constraint=models.UniqueConstraint(fields=('catégorie', 'nom_osm'), name='Une seule entrée pour chaque (catégorie, nom_osm).'),
        ),
        migrations.RenameModel(
            old_name='Amenity',
            new_name='Lieu',
        ),
        migrations.RenameModel(
            old_name='TypeAmenity',
            new_name='TypeLieu',
        ),
        migrations.RenameField(
            model_name='lieu',
            old_name='texte_tout',
            new_name='json_initial',
        ),
        migrations.AddField(
            model_name='bug',
            name='contact',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Contact (facultatif) : pour être tenu au courant du traitement de ceci.'),
        ),
        migrations.AddField(
            model_name='lieu',
            name='json_nettoyé',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='comment_reproduire',
            field=models.TextField(verbose_name='Comment obtenir le comportement non souhaité : '),
        ),
        migrations.AlterField(
            model_name='bug',
            name='message_d_erreur',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='(facultatif) Message d’erreur reçu :'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='ville',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.ville'),
        ),
        migrations.RenameField(
            model_name='lieu',
            old_name='type_amenity',
            new_name='type_lieu',
        ),
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='ville',
            name='densité',
        ),
        migrations.AddField(
            model_name='ville',
            name='superficie',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='ville',
            constraint=models.UniqueConstraint(fields=('nom_norm', 'code_insee'), name='Le couple (nom_norm, code_insee) doit être unique.'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='code_insee',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='arête',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dijk.arête'),
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='rue',
        ),
        migrations.AddField(
            model_name='lieu',
            name='adresse',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cache_adresse',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='cache_adresse',
            constraint=models.UniqueConstraint(fields=('adresse', 'ville'), name='Une seule entrée pour chaque (adresse, ville).'),
        ),
        migrations.RemoveField(
            model_name='arête',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='sommet',
            name='zone',
        ),
        migrations.AddField(
            model_name='sommet',
            name='villes',
            field=models.ManyToManyField(to='dijk.ville'),
        ),
        migrations.AddField(
            model_name='arête',
            name='villes',
            field=models.ManyToManyField(to='dijk.ville'),
        ),
        migrations.CreateModel(
            name='ArbreArête',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borne_sud', models.FloatField()),
                ('borne_ouest', models.FloatField()),
                ('borne_nord', models.FloatField()),
                ('borne_est', models.FloatField()),
                ('père', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_manager_fils', to='dijk.arbrearête')),
            ],
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='zone',
            name='arbre_arêtes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dijk.arbrearête'),
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='adresse',
        ),
        migrations.AddField(
            model_name='ville',
            name='lieux_calculés',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='SegmentArête',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_lon', models.FloatField()),
                ('d_lat', models.FloatField()),
                ('a_lon', models.FloatField()),
                ('a_lat', models.FloatField()),
                ('arête', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='dijk.arête')),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_manager_segment', to='dijk.arbrearête')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeTypeLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('type_lieu', models.ManyToManyField(to='dijk.typelieu')),
                ('féminin', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lieu',
            name='nom_norm',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='json_nettoyé',
        ),
        migrations.RenameField(
            model_name='lieu',
            old_name='json_initial',
            new_name='json_tout',
        ),
        migrations.AddField(
            model_name='lieu',
            name='autre_nom',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='inclue_dans',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_manager_sous_zones', to='dijk.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='cycla_max',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='zone',
            name='cycla_min',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lieu',
            name='num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
